name: vectorAI
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _tflow_select=2.3.0
  - abseil-cpp=20210324.2
  - absl-py=0.13.0
  - aiohttp=3.7.4.post0
  - altair=4.1.0
  - argh=0.26.2
  - argon2-cffi=21.1.0
  - arrow-cpp=3.0.0
  - astor=0.8.1
  - astunparse=1.6.3
  - async-timeout=3.0.1
  - async_generator=1.10
  - attrs=21.2.0
  - aws-c-common=0.4.57
  - aws-c-event-stream=0.1.6
  - aws-checksums=0.1.9
  - aws-sdk-cpp=1.8.185
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - base58=2.1.0
  - blas=1.0
  - bleach=4.1.0
  - blinker=1.4
  - boost-cpp=1.69.0
  - boto3=1.19.5
  - botocore=1.22.5
  - bottleneck=1.3.2
  - brotli=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2021.10.26
  - cachetools=4.2.2
  - certifi=2021.10.8
  - cffi=1.14.6
  - chardet=4.0.0
  - charset-normalizer=2.0.4
  - click=7.1.2
  - coverage=5.5
  - cryptography=3.4.8
  - cycler=0.10.0
  - cython=0.29.24
  - dataclasses=0.8
  - dbus=1.13.18
  - debugpy=1.4.1
  - decorator=5.1.0
  - defusedxml=0.7.1
  - double-conversion=3.1.5
  - entrypoints=0.3
  - expat=2.4.1
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freetype=2.10.4
  - gast=0.4.0
  - gflags=2.2.2
  - giflib=5.2.1
  - gitdb=4.0.9
  - gitpython=3.1.24
  - glib=2.69.1
  - glog=0.5.0
  - google-auth=1.33.0
  - google-auth-oauthlib=0.4.4
  - google-pasta=0.2.0
  - grpc-cpp=1.39.0
  - grpcio=1.36.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h5py=2.10.0
  - hdf5=1.10.6
  - icu=58.2
  - idna=3.2
  - importlib-metadata=4.8.1
  - intel-openmp=2021.3.0
  - ipykernel=6.4.2
  - ipython=7.28.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.5
  - jedi=0.18.0
  - jinja2=3.0.2
  - jmespath=0.10.0
  - joblib=1.0.1
  - jpeg=9d
  - jsonschema=4.1.2
  - jupyter_client=7.0.6
  - jupyter_core=4.9.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.2
  - kafka-python=2.0.2
  - keras-preprocessing=1.1.2
  - kiwisolver=1.3.1
  - krb5=1.19.2
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libblas=3.9.0
  - libboost=1.73.0
  - libcblas=3.9.0
  - libcurl=7.79.1
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - liblapack=3.9.0
  - libnghttp2=1.43.0
  - libpng=1.6.37
  - libprotobuf=3.17.2
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libstdcxx-ng=9.3.0
  - libthrift=0.14.2
  - libtiff=4.2.0
  - libuuid=1.0.3
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - libxcb=1.14
  - libxml2=2.9.12
  - llvm-openmp=12.0.1
  - lz4-c=1.9.3
  - markdown=3.3.4
  - markupsafe=2.0.1
  - matplotlib=3.4.3
  - matplotlib-base=3.4.3
  - matplotlib-inline=0.1.3
  - mistune=0.8.4
  - mkl=2021.3.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - multidict=5.1.0
  - munkres=1.1.4
  - nbclient=0.5.4
  - nbconvert=6.2.0
  - nbformat=5.1.3
  - ncurses=6.2
  - nest-asyncio=1.5.1
  - notebook=6.4.5
  - numexpr=2.7.3
  - numpy=1.21.3
  - oauthlib=3.1.1
  - olefile=0.46
  - openssl=1.1.1l
  - opt_einsum=3.3.0
  - orc=1.6.9
  - packaging=21.0
  - pandas=1.2.5
  - pandoc=2.15
  - pandocfilters=1.5.0
  - parso=0.8.2
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.4.0
  - pip=21.2.4
  - prometheus_client=0.11.0
  - prompt-toolkit=3.0.21
  - protobuf=3.17.2
  - ptyprocess=0.7.0
  - pyarrow=3.0.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.20
  - pydeck=0.7.1
  - pygments=2.10.0
  - pyjwt=2.1.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.9.7
  - python-dateutil=2.8.2
  - python-flatbuffers=2.0
  - python-tzdata=2021.5
  - python_abi=3.9
  - pytz=2021.3
  - pytz-deprecation-shim=0.1.0.post0
  - pyyaml=6.0
  - pyzmq=19.0.2
  - qt=5.9.7
  - re2=2021.08.01
  - readline=8.1
  - requests=2.26.0
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - s3transfer=0.5.0
  - scikit-learn=0.24.2
  - scipy=1.7.1
  - seaborn=0.11.2
  - send2trash=1.8.0
  - setuptools=58.0.4
  - sip=4.19.13
  - six=1.16.0
  - smmap=3.0.5
  - snappy=1.1.8
  - sqlite=3.36.0
  - streamlit=1.1.0
  - tensorboard=2.4.0
  - tensorboard-plugin-wit=1.6.0
  - tensorflow=2.4.1
  - tensorflow-base=2.4.1
  - tensorflow-estimator=2.6.0
  - termcolor=1.1.0
  - terminado=0.12.1
  - testpath=0.5.0
  - threadpoolctl=2.2.0
  - tk=8.6.11
  - toml=0.10.2
  - toolz=0.11.1
  - tornado=6.1
  - traitlets=5.1.1
  - typing-extensions=3.10.0.2
  - typing_extensions=3.10.0.2
  - tzdata=2021e
  - tzlocal=4.0.2
  - uriparser=0.9.3
  - urllib3=1.26.7
  - utf8proc=2.6.1
  - validators=0.18.2
  - watchdog=2.1.6
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=2.0.1
  - wheel=0.37.0
  - widgetsnbextension=3.5.1
  - wrapt=1.12.1
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.6.3
  - zeromq=4.3.4
  - zipp=3.6.0
  - zlib=1.2.11
  - zstd=1.4.9
